### ISSUE TITLE
Password Reset Causes 500 Error on Production

### ISSUE THREAD

**Issue by vkoves** [TransitTalk/Transit-Talk#108]
## Detailed Description

Trying to reset my password fails and throws a 500 error. Looking at Papertrail, I see this:

![screenshot from 2018-09-27 18-15-12](https://user-images.githubusercontent.com/3187531/46179548-5a847500-c281-11e8-8485-6c482c3a386e.png)

Considering I have fixed our SendGrid account and updated all of the credentials, this is likely an error in the prod configuration of SendGrid.

## Context

Resetting your password is an MVP feature that was deployed in PR #96, and should be working.

## Possible Implementation

See [SendGrid addon docs](https://devcenter.heroku.com/articles/sendgrid#actionmailer).

## Your Environment

Not relevant.

**Comment by vkoves** [comment]
@AcademyInPeril  - can you unassign me from this issue? I don't think I'll be taking it on in the near future

**Comment by vkoves** [comment]
@AcademyInPeril - pinging you on this

**Comment by EvanGrillo** [comment]
Password reset to work without error will require that we set up a mailer - would be happy to work on this

**Comment by vkoves** [comment]
Fixed in #173, which I confirmed on prod, so I am closing this issue as fixed!
