### ISSUE TITLE
Implement MVP UI

### ISSUE THREAD

**Issue by AcademyInPeril** [TransitTalk/Transit-Talk#130]
Prior to launch of our minimum viable product, we will make the switch to a new UI designed primarily by @shrubin2, including a new issue report form flow.

## Detailed Description
We must implement the new UI available [here](https://www.figma.com/file/GqwMkGtzeA7DgWWW0BoV3DLi/transittalk). The most complex changes will be on the issue reporting form, so anybody new to the project CSS may want to start on the homepage instead.

## Context
Prior to the launch of Transit Talk, we want to make our issue reporting form and other aspects of the site more useful and more recognizable. This new UI design will allow us to do so.

## Possible Implementation
This will be a lot of CSS work, with some additional Rails development for things like the moving category designations away from a dropdown on the issue reporting page.

## A note on style sheets and component uniformity (from Scott)
On the figma site (https://www.figma.com/file/GqwMkGtzeA7DgWWW0BoV3DLi/transittalk?node-id=0%3A1) there are components on the upper left side of the plane. Component titles are written above the shape and in the layer panel on the far left panel. You can see how components their instances/derivatives are kept consistent throughout the app, and this should be useful in establishing CSS uniformity.

**Comment by andreanthony** [comment]
is all the CSS located in the Transit-Talk-master/app/assets/stylesheets folder?

**Comment by shrubin2** [comment]
Hey Andre,
Yeah, all css files are in the stylesheets folder.

**Comment by tkimia** [comment]
Picking this up

**Comment by AcademyInPeril** [comment]
Closing in favor of a group of more specific issues that have replaced it, including #161 and #161
