### ISSUE TITLE
Routing/DB Definition Change: Remove Login Barrier for Reporting

### ISSUE THREAD

**Issue by AcademyInPeril** [TransitTalk/Transit-Talk#134]
In keeping with the open philosophy of the platform (and the need for issue reports to be timely), we don't want users to have to register an account before creating a report.

## Detailed Description
We will keep a username/password system in place, but it will be optional. This means that all routes that lead to and through issue report forms must be reconfigured to remove login barriers, and reports should autofill a sentinel user ID rather than a real one when a report is created by a user who isn't logged in. This may require some DB definition changes, or the addition of a dummy user entry to use as a sentinel. However, an account creation/login barrier should remain in place for user profile customization (i.e. setting "favorite" stops), since those settings are necessarily associated with accounts.

## Context
We believe that it's important to remove barriers to creating an issue report on Transit Talk. A user should not have to be logged in to be able to report an issue on the platform.

## Possible Implementation
Generally, this will involve reconfiguring existing routes to remove user login requirements from issue reporting. Depending on individual developer preference, this could also involve a schema change or the addition of a dummy user for sentinel user ID values in issue reports.

**Comment by aryzach** [comment]
I created a possible solution. The 'user' field in the issue model is optional, and the redirect to Sign In / Sign Up (when trying to create a new issue when not signed in) is removed. 

A better solution would be to still have the redirect to Sign In / Sign Up, but have an option to create an issue without logging in on that page. I'm still working on that solution

**Comment by AcademyInPeril** [comment]
@aryzach, sorry I'm just seeing this now. Let's go ahead and remove the redirect entirely, so that there's not an additional click that a user has to go through in order to create a report. Later on, we can do something like adding a message at the end of an issue submission that asks if they want to create or log into an account.
