### ISSUE TITLE
UI Implementation: Viewing Issue Reports

### ISSUE THREAD

**Issue by AcademyInPeril** [TransitTalk/Transit-Talk#162]
Complete UI implementation for viewing active issue reports on Transit Talk, based on [our Figma wireframes](https://www.figma.com/file/GqwMkGtzeA7DgWWW0BoV3DLi/transittalk?node-id=0%3A1).

## Detailed Description
The first version of these changes should replace the current All Lines page and its child pages. Additional logic will have to be built to filter results based on individual user preferences when a user is logged in, but for now we should show reports along all lines and at all stations following the styling of the issues section on the right side of the wireframes. If any of the desired displays requires additional logic built out, please sound off on this Issue or in Slack!

## Context
These changes are necessary before the MVP is launched. They will provide a basis upon which we can iterate.

## Possible Implementation
Please follow what's laid out in the Figma board as closely as possible. If there are assets or stylesheets that should inherit from elsewhere or be shared with other pages, be sure to note that.

**Comment by ajblaida** [comment]
Made some progress, mainly styling.

Ignored some best practices, hacking it out now and will bring it in line later.

[Branch](https://github.com/TransitTalk/Transit-Talk/tree/view-issue-reports)
