### ISSUE TITLE
Logic: Add Saved Stops/Lines for User Profiles

### ISSUE THREAD

**Issue by AcademyInPeril** [TransitTalk/Transit-Talk#163]
A user should be able to select a subset of lines or stops on Transit Talk to display by default on the application's homepage when logged in. None of the page displays or front end have to be built out as part of this issue; we simply want functions built to associate a list of specific lines and stops with their account as "Saved" lines/stops.

## Detailed Description
Logic must be built to associate a user with saved stops and lines, and to allow those saved stops and lines to be created, updated, and deleted.

## Context
This logic must be in place in order to implement the user preferences page (on which these settings will be set), the logged-in homepage (which will display issue reports filtered for the user's preferred stops and lines), and the logged-in Issues page (which will, by default, display issues corresponding to a user's preferred stops and lines first).

**Comment by vkoves** [comment]
@AcademyInPeril - is this different from favorites? I ask only because this seems very similar, and it might be tricky to distinguish between the two. We might also want to create a shared table for both if we do want both.

**Comment by AcademyInPeril** [comment]
This is the same thing. That feature was never fully implemented, but some of the table definitions are there. Tonight we discussed some details during the breakout group.
