### ISSUE TITLE
Pull accessibility data at the stop level (e.g. elevator outage)

### ISSUE THREAD

**Issue by jannielung** [TransitTalk/Transit-Talk#61]
1) Wheelchair accessibility data is not pulled at the stop/station level. Transitland data on wheelchair accessibility indicates only whether the vehicle (train or bus itself) is wheelchair accessible.
2) Wheelchair accessibility data needs to be added for transfers between two lines, i.e. Jackson blue/red line.

**Comment by tskelton88** [comment]
I suggest looking at reporting requirements for ADA compliance to FTA or other government oversight agencies. The agency reports may be public data and may be in an XML format that you can create a script to parse through and extract the accessibility data. That's just my gut sense/guess.
