### ISSUE TITLE
Create Admin user type, along with admin panel for issue deletion.

### ISSUE THREAD

**Issue by AcademyInPeril** [TransitTalk/Transit-Talk#72]
Add functionality to allow administrative users to delete existing issues and user accounts. This functionality should let admins see which user created each issue, so that patterns in erroneous or malicious issue reporting can be discovered.

**Comment by AcademyInPeril** [comment]
I have added the "good first issue" label because user account types are somewhat easily created and managed in Rails, and a new contributor could add this functionality to the admin panel without much trouble.

**Comment by brarnaudovski** [comment]
Hi. I want to work on this issue, but I need more info regarding the admin panel that is mention in the name of this issue.
I've notice that such think doesn't exist in the app as separate page/unit.

**Comment by vkoves** [comment]
@brarnaudovski -  there isn't one definitive admin panel right now, except for changing site settings. However, for the scope of this issue, I think making two pages for managing issues and users that are only accessible would be perfectly fine.

**Comment by AcademyInPeril** [comment]
Infrastructure has been put in place for this by @sinclairtarget, merged in #131.

**Comment by AcademyInPeril** [comment]
The scope of this issue has now been changed. We wish to have a user flag of some sort for admins, who have access to an admin panel on which they can delete any specific issue report from Transit Talk. Anybody working on this can take a look at Sinclair's old work on #131 to see if it can be built off of.

**Comment by AcademyInPeril** [comment]
This has been tackled by #139
