### ISSUE TITLE
Create Map View for Issues

### ISSUE THREAD

**Issue by SorenSpicknall** [TransitTalk/Transit-Talk#74]
Create a map view for viewing issues, along with settings for manipulating the map. A version of this view with default settings will be included on the top of the homepage (#73). Settings include time frame of issue display (most likely based on increments of backwards time for the MVP), region of display, and filters for the types of issues one wishes to view (including vehicle types).

More detailed information to come in further discussions, but this is an MVP component.

**Comment by vkoves** [comment]
Thanks for the clarification!
