### ISSUE TITLE
Logic: Add User Preferences/Settings

### ISSUE THREAD

**Issue by vkoves** [TransitTalk/Transit-Talk#92]
From the Caravan functional spec:

> Types of Issue Alerts Preferences screen -  has a general toggle to enable push notifications. Underneath this, there is a list of all of the issue types, and a user can toggle whether they are notified of that type of issue at their favorite stops. Ex: “Notify me of delays at my favorite stops”.

> There also should be two time ranges that can be used to restrict when a user receives notifications. Ex: “Only notify me between 9 AM and 10 AM OR between 6 PM  and 7 PM”

**Comment by AcademyInPeril** [comment]
This issue has been updated to include a broader range of tasks corresponding to the preferences page. Please refer to the current UI wireframes (https://marvelapp.com/g49gbf9/) to understand what settings need to be built out on that page, including saved "favorite" stations.

**Comment by AcademyInPeril** [comment]
Closing. This issue no longer describes the desired functionality.
